Import('*')

SimObject('DuetNN.py', sim_objects=[
    'DuetNNMemLane',
    'DuetNNComputeLane',
    'DuetNNReductionLane',
    'DuetNNStAckDrainLane',
    'DuetNNEngine'
    ])

Source('DuetNNMemFunctor.cc')
Source('DuetNNMemLane.cc')
Source('DuetNNComputeFunctor.cc')
Source('DuetNNComputeLane.cc')
Source('DuetNNReductionFunctor.cc')
Source('DuetNNReductionLane.cc')
Source('DuetNNStAckDrainFunctor.cc')
Source('DuetNNStAckDrainLane.cc')
Source('DuetNNEngine.cc')
