Import('*')

SimObject('DuetEngine.py', sim_objects=['DuetEngine'])
SimObject('DuetLane.py', sim_objects=['DuetLane', 'DuetSimpleLane'])

Source('DuetFunctor.cc')
Source('DuetLane.cc')
Source('DuetSimpleLane.cc')
Source('DuetEngine.cc')
