Import('*')

SimObject('DuetFmmVLI.py', sim_objects=[
    'DuetFmmVLIFrontendLane',
    'DuetFmmVLIComputeLane',
    'DuetFmmVLIBackendLane',
    'DuetFmmVLIEngine'
    ])

Source('DuetFmmVLIBackendFunctor.cc')
Source('DuetFmmVLIBackendLane.cc')
Source('DuetFmmVLIComputeFunctor.cc')
Source('DuetFmmVLIComputeLane.cc')
Source('DuetFmmVLIEngine.cc')
Source('DuetFmmVLIFrontendFunctor.cc')
Source('DuetFmmVLIFrontendLane.cc')
