Import('*')

SimObject('DuetDriver.py', sim_objects=['DuetDriver'])
SimObject('DuetAsyncFIFO.py', sim_objects=['DuetAsyncFIFOCtrl', 'DuetAsyncFIFO'])
SimObject('DuetPipeline.py', sim_objects=['DuetPipeline'])
SimObject('DuetClockedObject.py', sim_objects=['DuetClockedObject'])

Source('DuetDriver.cc')
Source('DuetAsyncFIFOCtrl.cc')
Source('DuetAsyncFIFO.cc')
Source('DuetPipeline.cc')
Source('DuetClockedObject.cc')

DebugFlag('DuetDriver')
DebugFlag('DuetAsyncFIFO')
DebugFlag('DuetPipeline')
