Import('*')

SimObject('DuetBarnesQuad.py', sim_objects=[
    'DuetBarnesQuadMemLane',
    'DuetBarnesQuadComputeLane',
    'DuetBarnesQuadEngine'
    ])

Source('DuetBarnesQuadMemFunctor.cc')
Source('DuetBarnesQuadMemLane.cc')
Source('DuetBarnesQuadComputeFunctor.cc')
Source('DuetBarnesQuadComputeLane.cc')
Source('DuetBarnesQuadEngine.cc')
