Import('*')

SimObject('DuetKNN.py', sim_objects=[
    'DuetKNNMemLane',
    'DuetKNNComputeLane',
    'DuetKNNEngine'
    ])

Source('DuetKNNMemFunctor.cc')
Source('DuetKNNMemLane.cc')
Source('DuetKNNComputeFunctor.cc')
Source('DuetKNNComputeLane.cc')
Source('DuetKNNEngine.cc')
